### PR TITLE
Javier updating readme

### PR DESCRIPTION
**Pull request by JavierGOrdonnez**
Testing the approval mechanism of GitHub.

### CODE REVIEW

**Review by newton1985 — CHANGES_REQUESTED** [review]
It needs a bit more flair - maybe some animations? :)

**Comment by newton1985** [comment]
P.S. this is a good exercise for me to really get familiar with using the collaborative features of github.

**Comment by JavierGOrdonnez** [comment]
open for ideas for the future. But probably it would be nice to finish this merge request, it is just indeed to get more familiar with these collaborative features and not mess up when we are collaborating on real work among ourselves or with external people (or at least, make most of the newbie mistakes now)

**Review by newton1985 — APPROVED** [review]
Looks good.

**Pull request merged**
